package geometries.api;

import primitives.Color;
import primitives.Material;
import primitives.Point;
import primitives.Vector;

/**
 * Abstract base class for all geometric shapes.
 * Extends Intersectable and adds visual properties like emission color and material.
 */
public abstract class Geometry extends Intersectable {

    /**
     * The emission color of the geometry (light generated by the object itself)
     */
    private Color emission = Color.BLACK;
    /**
     * The material properties of the geometry governing light interaction
     */
    private Material material = new Material();

    /**
     * Empty default constructor for documentation tools.
     */
    public Geometry() {
        /* Empty default constructor for documentation tools. */
    }

    /**
     * Gets the emission color of the geometry.
     *
     * @return the emission color
     */
    public Color getEmission() {
        return emission;
    }

    /**
     * Sets the emission color of the geometry.
     *
     * @param emission the new emission color
     * @return this Geometry object for method chaining
     */
    public Geometry setEmission(Color emission) {
        this.emission = emission;
        return this;
    }

    /**
     * Gets the material properties of the geometry.
     *
     * @return the material object
     */
    public Material getMaterial() {
        return material;
    }

    /**
     * Sets the material properties of the geometry.
     *
     * @param material the new material configuration
     * @return this Geometry object for method chaining
     */
    public Geometry setMaterial(Material material) {
        this.material = material;
        return this;
    }

    /**
     * Calculates the normal vector to the geometry at a specific point.
     *
     * @param point the point on the geometry surface
     * @return The normal vector at that point
     */
    public abstract Vector getNormal(Point point);
}
