package renderer;

import static java.awt.Color.BLUE;
import static java.awt.Color.RED;

import org.junit.jupiter.api.Test;

import geometries.api.Intersectable;
import geometries.impl.Sphere;
import geometries.impl.Triangle;
import lighting.AmbientLight;
import lighting.SpotLight;
import primitives.Color;
import primitives.Material;
import primitives.Point;
import primitives.Vector;
import scene.Scene;

/**
 * Testing basic shadows
 * @author Dan Zilberstein
 */
@SuppressWarnings("java:S109")
class ShadowTests {
   /** Default constructor to satisfy JavaDoc generator */
   ShadowTests() { /* to satisfy JavaDoc generator */ }

   /** Scene of the tests */
   private final Scene          _scene         = new Scene("Test scene");
   /** Camera builder of the tests */
   private final Camera.Builder _cameraBuilder = Camera.getBuilder()
      .setLocation(new Point(0, 0, 1000))
      .setVpDistance(1000)
      .setVpSize(200, 200)
      .setDirection(Point.ZERO, Vector.AXIS_Y)
      // .setDirection(new Point(-8, -78, 0), Vector.AXIS_Y) // debug
      .setResolution(600, 600)
      .setRayTracer(_scene, RayTracerType.SIMPLE);

   /** The sphere in the tests */
   private final Intersectable  _sphere        = new Sphere(new Point(0, 0, -200), 60D)
      .setEmission(new Color(BLUE))
      .setMaterial(new Material().setKd(0.5).setKs(0.5).setShininess(99));
   /** The material of the triangles in the tests */
   private final Material       _trMaterial    = new Material().setKd(0.5).setKs(0.5).setShininess(30);

   /**
    * Helper function for the tests in this module
    * @param pictName     the name of the picture generated by a test
    * @param triangle     the triangle in the test
    * @param spotLocation the spotlight location in the test
    */
   private void sphereTriangleHelper(String pictName, Triangle triangle, Point spotLocation) {
      _scene.geometries.add(_sphere, triangle.setEmission(new Color(BLUE)).setMaterial(_trMaterial));
      _scene.lights //
         .add(new SpotLight(new Color(400, 240, 0), spotLocation, new Vector(1, 1, -3)) //
            .setKl(1E-5).setKq(1.5E-7));
      renderSceneToImage(pictName, false, false);
   }

   /**
    * Perform final rendering of a picture
    * @param pictName       the picture file name
    * @param multiThreading true if multi-threading is required, false otherwise
    * @param grid           true if grid is required, false otherwise
    */
   private void renderSceneToImage(String pictName, boolean multiThreading, boolean grid) {
      // if (multiThreading)
      // _cameraBuilder.setMultithreading(-1).setDebugPrint(1);
      var camera = _cameraBuilder.build().renderImage();
      if (grid) camera.printGrid(30, new Color(RED));
      camera.writeToImage(pictName);
   }

   /** Produce a picture of a sphere and triangle with point light and shade */
   @Test
   void testSphereTriangleInitial() {
      sphereTriangleHelper("shadowSphereTriangleInitial", //
                           new Triangle(new Point(-70, -40, 0), new Point(-40, -70, 0), new Point(-68, -68, -4)), //
                           new Point(-100, -100, 200));
   }

   /** Sphere-Triangle shading - move triangle up-right */
   @Test
   void testSphereTriangleMove1() {
      sphereTriangleHelper("shadowSphereTriangleMove1", //
                           new Triangle(new Point(-60, -30, 0), new Point(-30, -60, 0), new Point(-58, -58, -4)), //
                           new Point(-100, -100, 200));
   }

   /** Sphere-Triangle shading - move triangle upper-righter */
   @Test
   void testSphereTriangleMove2() {
      sphereTriangleHelper("shadowSphereTriangleMove2", //
                           new Triangle(new Point(-50, -20, 0), new Point(-20, -50, 0), new Point(-48, -48, -4)), //
                           new Point(-100, -100, 200));
   }

   /** Sphere-Triangle shading - move spot closer */
   @Test
   void testSphereTriangleSpot1() {
      sphereTriangleHelper("shadowSphereTriangleSpot1", //
                           new Triangle(new Point(-70, -40, 0), new Point(-40, -70, 0), new Point(-68, -68, -4)), //
                           new Point(-90, -90, 150));
   }

   /** Sphere-Triangle shading - move spot even more close */
   @Test
   void testSphereTriangleSpot2() {
      sphereTriangleHelper("shadowSphereTriangleSpot2", //
                           new Triangle(new Point(-70, -40, 0), new Point(-40, -70, 0), new Point(-68, -68, -4)), //
                           new Point(-80, -80, 100));
   }

   /**
    * Produce a picture of a two triangles lighted by a spot light with a Sphere
    * producing a shading
    */
   @Test
   void testTrianglesSphere() {
      setTrianglesSphereScene();
      _scene.lights.add(createSpotForTrianglesSpere());
      renderSceneToImage("shadowTrianglesSphere", false, false);
   }

   /**
    * Prepare the Spotlight for the Sphere over a couple of Triangles test
    * @return the spotlight object
    */
   private static SpotLight createSpotForTrianglesSpere() {
      return new SpotLight(new Color(700, 400, 400), //
                           new Point(40, 40, 115), //
                           new Vector(-1, -1, -1)) //
         .setKl(1E-6).setKq(1E-12);
   }

   /**
    * Prepare the 3D model for the Sphere over a couple of Triangles test
    */
   private void setTrianglesSphereScene() {
      Material triangleMaterial = new Material().setKd(0.2).setKs(0.4).setShininess(111);
      _scene.geometries //
         .add( //
              new Triangle(new Point(-150, -150, -115), new Point(150, -150, -135), new Point(75, 75, -150)) //
                 .setMaterial(triangleMaterial), //
              new Triangle(new Point(-150, -150, -115), new Point(-70, 70, -140), new Point(75, 75, -150)) //
                 .setMaterial(triangleMaterial), //
              new Sphere(new Point(0, 0, -11), 30D) //
                 .setEmission(new Color(BLUE)) //
                  .setMaterial(new Material().setKd(0.5).setKs(0.4).setShininess(111)) //
         );
      _scene.setAmbientLight(new AmbientLight(new Color(38, 38, 38)));
   }

}
